### ISSUE TITLE
Разработка библиотеки

### ISSUE THREAD

**Issue by artem-prozorov** [zebrainsteam/laravel-repos#1]
Необходимо сделать адаптер для Laravel для библиотеки https://github.com/artem-prozorov/repos

Функциональные требования:

1. Публикация сервис провайдера из команды
2. Автоматическая генерация EloquentRepository для классов-потомков Model
3. Генерация классов-репозиториев

Детальная задача:
1. Нужно разработать класс-репозиторий для работы с Eloquent. Наследовать его от этого класса: https://github.com/artem-prozorov/repos/blob/master/src/AbstractRepository.php
(вообще верхнеуровнево вот контракт для репозитория https://github.com/artem-prozorov/repos/blob/master/src/Contracts/RepositoryInterface.php). Должна быть возможность передать класс модели в конструктор.
2. Нужно наладить работу фабрики репозиториев (https://github.com/artem-prozorov/repos/blob/master/src/RepositoryFactory.php) с ларавелевским контейнером. Для этого нужно в фабрику передать резолвер (https://github.com/artem-prozorov/repos/blob/master/src/Resolvers/ContainerAwareResolver.php) в конструктор которого прокинут ларавелевский контейнер
3. Для автоматической генерации репозитории для модели нужно реализовать свой резолвер (вот интерфейс https://github.com/artem-prozorov/repos/blob/master/src/Contracts/ResolverInterface.php). Этот резолвер должен проверять, запрошен ли репозиторий для модели Элоквент, и если отдельно такого репозитория нет, то создавать его динамически (создать элоквент репозиторий и прокинуть в конструктор класс модели).
Далее нужно использовать вот этот резолвер https://github.com/artem-prozorov/repos/blob/master/src/Resolvers/ChainResolver.php чтобы фактически подключить сперва свой резолвер, потом резолвер контейнера

**Comment by manzor29** [comment]
Уточнение по п.3:
Как ты видишь механизм определения резолвером наличия уже созданного репозитория? Например, я создал специфичный репозиторий для класса App\User - App\Repositories\UserRepository. Затем с помощью нового резолвера пытаюсь создать репозиторий:
`
$repoForUsers = $superResolver->resolve(User::class);
`
ожидая получить экземпляр класса App\Repositories\UserRepository. Для этого внутри резолвера надо реализовать получение из контейнера (с помощью ContainerAwareResolver) класса с таким названием при его наличии, т.е. по принципу "App\Repositories\<название модели>Repository? Т.о. предполагается какое-то соглашение об именовании специфичных репозиториев? Как вариант можно использовать конфиг с мэппингом моделей и созданных для них специфичных репозиториев; тогда определение наличия уже созданного репозитория можно будет реализовать поиском в этом конфиге по названию модели.

**Comment by artem-prozorov** [comment]
Я вижу тут 2 варианта:
1. Фабрике репозиториев можно давать конфиг в любом формате, не обязательно делать привязку к классам. Например, можно сделать так: `'user_repostory' => \App\Repositories\User::class` и тогда запрашивать так: `$superResolver->resolve('user_repository');`. То есть, можно указывать конфиг так: `\App\Models\User::class => \App\Repositories\User::class`. В этом случае ничего делать не нужно, это уже реализовано в базовой библиотеке.

2. Второй вариант чуть более интересный. Можно сделать интерфейс HasRepository, примерно следующего содержания:
```
interface HasRepository
{
    public function getRepository(): EloquentRepostory;
}
```
и потом внутри EloquentAutoResolver проверять, является ли заданная модель экземпляром этого класса. Если является, то возвращать тот репозиторий, который возвращается методом `getRepository`.

**Comment by artem-prozorov** [comment]
Ну то есть получается, у EloquentAutoResolver алгоритм примерно такой:
1. Реализует ли заданный класс интерфейс HasRepository, если да - вернуть то, что приходит из метода getRepository
2. Проверить, является ли заданный класс базовой моделью Eloquent. Если да, то создать EloquentRepository с этой моделью
3. Выбросить исключение

**Comment by artem-prozorov** [comment]
Базовая часть выполнена, закрываю задачу
