### ISSUE TITLE
Должна быть возможность сгенерировать интерфейс для репозитория через консольную команду

### ISSUE THREAD

**Issue by artem-prozorov** [zebrainsteam/laravel-repos#2]
1. Должна быть консольная команда для генерации интерфейса для репозитория
2. У консольной команды для генерации репозитория должен быть аргумент --with-interface который, если указан, генерировал бы сразу интерфейс к создаваемому репозиторию

**Comment by manzor29** [comment]
Вопросы:
1. автоматически генерируемый репозиторий должен наследоваться от Prozorov\Repositories\AbstractRepository или просто имплементировать какой-то интерфейс из Prozorov\Repositories или вообще не использовать другие классы/интерфейсы?
2. если при генерации репозитория указан аргумент --with-interface, то мы создаем абсолютно новый интерфейс или наследуем новый интерфейс от какого-то из Prozorov\Repositories

**Comment by artem-prozorov** [comment]
Отличный вопрос. Предлагаю следующее:

1. Давай добавим 2 шаблона: первый наследуется от `Prozorov\Repositories\AbstractRepository`, а второй - от `Prozorov\Repositories\Contracts\RepositoryInterface`. Поведение по умолчанию - создавать класс первого типа. И добавим аргумент, например `--from-interface`, при указании которого будет создаваться класс второго типа (наследующийся только от интерфейса)

2. Мы создаем новый интерфейс, расширяющий `Prozorov\Repositories\Contracts\RepositoryInterface`, и создаем новый класс, который будет наследоваться уже от нового интерфейса. При этом, первое правило работает.

На примерах:
1. Генерируем репозиторий, указываем его название без неймспейса: `php artisan repository:make UserRepository`
Ожидаемый результат: создастся класс `App\Repositories\UserRepository`, наследующийся от `Prozorov\Repositories\AbstractRepository`
2. Генерируем репозиторий, указываем полный неймспейс: `php artisan repository:make \\App\\Services\\User\\Repository`
Ожидаемое поведение: создастся класс `App\Services\User\Repository`, наследующийся от `Prozorov\Repositories\AbstractRepository`. При этом, структура папок создастся, если папки в файловой системе не существуют.
3. Генерируем репозиторий, указываем аргумент --with-interface `php artisan repository:make --with-interface UserRepository`
Ожидаемое поведение: создастся интерфейс `App\Contracts\UserRepositoryContract`, расширяющий `Prozorov\Repositories\Contracts\RepositoryInterface` (но не содержащий никаких методов). Создастся также репозиторий `App\Repositories\UserRepository`, наследующийся от `Prozorov\Repositories\AbstractRepository` и реализующий этот новый интерфейс.
4. Генерируем репозиторий, передаем путь к нужному интерфейсу `php artisan repository:make --with-interface \\App\\Services\\UserReposioryInterface UserRepository`
Ожидаемое поведение: как в пункте 3, только интерфейс будет создан `App\Services\UserReposioryInterface`
5. Генерируем репозиторий, указываем команду `--from-interface`. Ожидаемое поведение: создастся репозиторий `App\Repositories\UserRepository`, не наследующийся ни от чего и только лишь реализующий интерфейс `Prozorov\Repositories\Contracts\RepositoryInterface`. Все методы из интерфейса присутствуют, но пустые (заготовка)
6. Генерируем репозиторий, указываем команду `--from-interface`, указываем аргумент `--with-interface`. `php artisan repository:make --from-interface --with-interface \\App\\Interfaces\\UserRepositoryContract UserRepository`.
Ожидаемое поведение: Создастся интерфейс App\Interfaces\UserRepositoryContract и класс App\Repositories\UserRepository, который будет в точности как в пункте 5, только реализовывать интерфейс \\App\\Interfaces\\UserRepositoryContract

**Comment by manzor29** [comment]
Предлагаю следующие дополнения к постановке:
1. Использовать команду `make:repository` вместо `repository:make`, т.к. это больше соответствует используемому синтаксису штатных команд Ларавеля по генерации;
2. Ввести такое соглашение по указанию имени репозитория/интерфейса в команде: если имя начинается с `/`, то нэймспейс формируем от корневого (`App\`); иначе нэймспейс формируем от дефолтного (для репозитория - `App\Repositories\`, для интерфейсов - `App\Contracts\Repository\`);
3. Указывать имя репозитория вначале команды, т.к., во-первых, оно должно присутствовать всегда; во-вторых, в таком случае наличие имени интерфейса трактовать как необходимость создания кастомного класса интерфейса. Тогда, например в п.6. можно будет не использовать параметр `--with-interface`, а просто указать:
`php artisan make:repository UserRepository --from-interface /Interfaces/UserRepositoryContract `

**Comment by artem-prozorov** [comment]
Противоречий нет

**Comment by artem-prozorov** [comment]
Задача выполнена, закрываю
